// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSTJ6H2ntPFIydSZEgYV_p_G2LTj08-Jo',
    appId: '1:529388072551:web:1b18bf8e85d792c459aec2',
    messagingSenderId: '529388072551',
    projectId: 'yazn-e0652',
    authDomain: 'yazn-e0652.firebaseapp.com',
    storageBucket: 'yazn-e0652.appspot.com',
    measurementId: 'G-ZPZ3B1KX16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDNUfvr4W6sQxW4Kq2JbqP_0IeWF22Ec',
    appId: '1:529388072551:android:a80b063ef8096e9259aec2',
    messagingSenderId: '529388072551',
    projectId: 'yazn-e0652',
    storageBucket: 'yazn-e0652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF07Xm1J53m3R9DppKn-KeKTyYBx9ADTs',
    appId: '1:529388072551:ios:92618e51d39c271b59aec2',
    messagingSenderId: '529388072551',
    projectId: 'yazn-e0652',
    storageBucket: 'yazn-e0652.appspot.com',
    iosClientId: '529388072551-g4gaonanjebddc9biqlhbd587vfggnip.apps.googleusercontent.com',
    iosBundleId: 'com.example.playingWithFlutter',
  );
}
